function sensitivityMethods = getSensitivityMethods
    
    sensitivityMethods = {'analytic (symbolic)',...
                          'finite differences', ...
                          'automatic differentiation'...   
                         };
end
