% Calculate euclidean Gradient of log-likelihood with respect to parameters
% see eqn 5.6 in the thesis for derivation of LL gradient
function gradient_LL = LL_Gradient(...
                                    sampledParameters,  Sensitivities_1,... 
                                    numSampledParams,   SpeciesObserved,... 
                                    NumTimePts,         speciesEstimates,... 
                                    Y,                  CurrentNoise,...
                                    prior_derivative...
                                  )
                                   
    gradient_LL = zeros(1, numSampledParams);
    for ParaNum = 1: numSampledParams
        for i = SpeciesObserved            
            gradient_LL(ParaNum) = gradient_LL(ParaNum) + ...
                                                          ...
            sum(... 
                - ((speciesEstimates(i, :) - Y(i, :)) .*...
                    Sensitivities_1{ParaNum}(:, i)'... 
                  )... 
                  ./ ((ones(1, NumTimePts)*CurrentNoise(i)))... 
               );
        end
        gradient_LL(ParaNum) = gradient_LL(ParaNum) + ...
                               prior_derivative( ParaNum, ...
                                                 sampledParameters(ParaNum)...
                                               );
    end % for   
end % function     
