% Calculate euclidean Gradient of log-likelihood with respect to parameters
% see eqn 5.6 in the thesis for derivation of LL gradient
function gradient_LL = LL_Gradient(...
                                    sampledParameters,  sensitivities_1,... 
                                    numSampledParams,   speciesObserved,... 
                                    numTimePts,         speciesEstimates,... 
                                    Y,                  currentNoise,...
                                    priorDerivative...
                                  )
                                   
    gradient_LL = zeros(1, numSampledParams);
    for ParaNum = 1: numSampledParams
        for i = speciesObserved            
            gradient_LL(ParaNum) = gradient_LL(ParaNum) + ...
                                                          ...
            sum(... 
                - ((speciesEstimates(i, :) - Y(i, :)) .*...
                    sensitivities_1{ParaNum}(:, i)'... 
                  )... 
                  ./ ((ones(1, numTimePts)*currentNoise(i)))... 
               );
        end
        gradient_LL(ParaNum) = gradient_LL(ParaNum) + ...
                               priorDerivative( ParaNum, ...
                                                 sampledParameters(ParaNum)...
                                              );
    end % for   
end % function     
