% Calculates the partial derivatives of the metric tensor used in 
% Laplace Beltrami Operator

function GDeriv = metric_Tensor_Deriviatives...
                   (... 
                     Sensitivities_1,   SpeciesObserved,...
                     Sensitivities_2,   numSampledParams,...
                     CurrentNoise,      sampledParameters,... 
                     prior_third_derivative...
                   )
    
    GDeriv = cell(1, numSampledParams);  
    
    for k = 1: numSampledParams
        % Allocate cell array for each value of k
        GDeriv{k} = zeros(numSampledParams,...
                          numSampledParams);
        
        % Use sensitivities
        % Follows from applying product rule on 
        % G(i,j) = sum_{species}(sens_i(species) * cov_mat * sens_j(species)) 
        for SpeciesNum_a = SpeciesObserved
            for i = 1: numSampledParams
                for j = 1: numSampledParams
                    
                    GDeriv{k}(i, j) = GDeriv{k}(i, j) + ...                    
                                                        ...
                    (Sensitivities_2{i, k}(:, SpeciesNum_a)'  *...
                     Sensitivities_1{j}(:, SpeciesNum_a)...                
                     / CurrentNoise(SpeciesNum_a)...
                    ) + ...
                        ...
                    (Sensitivities_1{i}(:, SpeciesNum_a)'     *...
                     Sensitivities_2{j, k}(:, SpeciesNum_a)... 
                     / CurrentNoise(SpeciesNum_a)...
                    );

                end
            end
        end
        
        % Add prior to the derivative of metric tensor
        % Follows from (log(posterior))_{theta,theta,theta}, third derivative of 
        % log(posterior). Note: this is a prior on a matrix of all sampled parameters        
        GDeriv{k}        = GDeriv{k} - ...
                           prior_third_derivative(numSampledParams,...
                                                  sampledParameters);                                  
    end % for    
        
end


